-- SQL seed dla tabeli players
-- Wygenerowano automatycznie

INSERT INTO players (name, team_id, position, price, health_status) VALUES
('Abdullahi Abbati', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Abramowicz Dawid', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Abramowicz Sławomir', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Adamczyk Hubert', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Adkonis Jakub', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Agnero Yannick', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Akere Samuel', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Al-Ammari Amir', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Aleksić Milan', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Ali Hussein', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Álvarez Fran', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Alves Roberto', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Ambros Lukáš', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Ambrosiewicz Maciej', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Ameyaw Michael', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Amorim Adriano', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Andréou Stélios', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Andrzejkiewicz Kamil', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Antczak Jakub', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Arreiol Henrique', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Arsenić Zoran', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Augustyniak Rafał', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Awad Alla Mohamed', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Ba Pape Meïssa', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Baena Ángel', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Bahonko Erwin', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Bajko Marcel', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 0.80, 'Pewny'),
('Balde Elves', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Bałabuch Antoni', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Barański Bartłomiej', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Baráth Baráth', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Barbosa Gabriel', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Barkowskij Gierman', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Barnowski Dawid', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.30, 'Pewny'),
('Baró Romário', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Bartoš Marek', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Bąkowski Krzysztof', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Bengtsson Leo', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Bergier Sebastian', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Biczachczjan Wahan', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Biedrzycki Bartosz', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Biegański Jan', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Biegański Mikołaj', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Bielka Adrian', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.80, 'Pewny'),
('Biniek Dominik', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Blasco Jérémy', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Błanik Dawid', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Błąd Adrian', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Bobček Tomáš', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Boboc Radu', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Bochniarz Kuba', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Boisgard Quentin', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Borges Léo', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Borowski Bartosz', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.80, 'Pewny'),
('Borowski Filip', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Bosch Jesse', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Braut Brunes Jonatan', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.50, 'Pewny'),
('Brkić Ivan', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Bród Alan', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 0.80, 'Pewny'),
('Brzęk Bartosz', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Budnicki Jakub', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Bulat Marko', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.30, 'Pewny'),
('Burch Marco', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Burek Jakub', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.00, 'Pewny'),
('Burić Jasmin', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Bzdyl Fabian', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Camará Ibrahima', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Cantero Alejandro', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Capemba Capita Osvaldo', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Carenko Anton', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Cebula Marcin', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Célestine Julien', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Charpentier Gabriel', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Chłań Maksym', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Chodyna Kacper', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Chovan Adrian', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Chrapek Michał', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Cichocki Mateusz', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Ciszek Konrad', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Cojocaru Valentin', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Čolak Antonio', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Custovic Kevin', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Cybulski Kamil', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Cymerys Konrad', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Czerwiński Alan', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Czerwiński Jakub', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Czubak Karol', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Czyż Szymon', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Ćirković Aleksandar', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Ćorluka Josip', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Ćwielong Kacper', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Dadaşov Renat', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Dalmau Adrián', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Damasiewicz Adrian', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Daniel Justin', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Davidović Stjepan', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Dąbrowski Damian', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Deisadze Diego', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.10, 'Pewny'),
('Diaby-Fadiga Lamine', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Diaczuk Maksym', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Diaz Jesus', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Diéguez Adrián', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Djaló Matchoi', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Długosz Wiktor', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Dombroski Thiago', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Donio Bastien', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Douglas Alex', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Dónis Chrístos', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Drachal Dawid', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Drapiński Igor', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Dudek Sammy', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Dziczek Patryk', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Dziekoński Xavier', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Dziewiatowski Mateusz', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Dzięgielewski Natan', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Ede Bright', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Edmundsson Andrias', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Elitim Juergen', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Espiau Edu', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Faßbender Morgan', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Félix Garcia Jorge', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Fiabema Bryan', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Flach Leon', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Fornalczyk Mariusz', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Fritzson Ludvig', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Galán Borja', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Gallapeni Dion', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Gaprindaszwili Tornike', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Gholizadeh Ali', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.80, 'Pewny'),
('Gikiewicz Rafał', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Glik Kamil', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Głogowski Michał', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Głowiński Mateusz', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Gmur Tymoteusz', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Goh Young-jun', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Gojny Dawid', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Golonka Konrad', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Gołębiewski Kacper', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Gonçalves Claude', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('González Plata David', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Greenwood Sam', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 2.40, 'Pewny'),
('Grobelny Jędrzej', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Grosicki Kamil', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 3.60, 'Pewny'),
('Gruszkowski Konrad', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Gryzio Daniel', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Grzejszczak Jakub', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Grzesik Jan', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Grzybek Mateusz', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Guerrero Sergio', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Gumny Robert', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Gurgul Michał', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Haglind-Sangré Marcus', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Håkans Daniel', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Hanousek Marek', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Harciński Krystian', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Hasić Ajdin', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Haxha Florian', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Hellebrand Patrik', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Henriksson Gustaw', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Heredia Antonin Antonio', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Hermoso Kike', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Hilbrycht Damian', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Hirosawa Toki', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Hiszpański Fabian', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Hładun Dominik', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Huja Marian', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Ilić Veljko', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Imaz Jesús', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 3.90, 'Pewny'),
('Ishak Mikael', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 4.10, 'Pewny'),
('Isik Gabriel', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Ismaheel Taofeek', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Jackson Aziel', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Jagiełło Filip', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Jakóbczyk Kamil', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Jakuba Roman', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Jakubczyk Kamil', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Jakubik Wojciech', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Jakubowski Rafał', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Janicki Rafał', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Janža Erik', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Jaroszek Bartosz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Jaunzems Alvis', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Jesionowski Borys', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Jędrych Arkadiusz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Jędrzejczyk Artur', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Jimenez Jesus', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Jiménez Jorge', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Jirka Erik', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Josema José Manuel', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Jóźwiak Kamil', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 2.30, 'Pewny'),
('Jugas Jakub', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Jurić Deni', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Juwara Musa', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kakabadze Otar', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kalandadze Aleksandre', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kałahur Miłosz', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kameri Dijon', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kamiński Krzysztof', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kamiński Marcin', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Kamiński Wojciech', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Kapić Rifet', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Kapuadi Steve', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Kapustka Bartosz', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Kaput Michał', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Karasek Kacper', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kardaś Adam', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Kasperkiewicz Arkadiusz', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Katsantónis Andréas', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Keramítsis Dimítrios', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kerk Sebastian', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kikolski Maciej', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kingué Steve', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Klat Oskar', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Klemenz Lukas', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Klich Mateusz', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Klon Oskar', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Klukowski Antoni', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.00, 'Pewny'),
('Kłudka Bartłomiej', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kmeť Matúš', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Knap Karol', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kobayashi Yūki', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kobylak Gabriel', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kocaba Filip', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Kocyła Dawid', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Koczerhin Władysław', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Kolan Jakub', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Kolasa Józef', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Kolec Bartłomiej', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Konik Patryk', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Konstantópoulos Apóstolos', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Kopacz Bartosz', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kopczyński Mateusz', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Koperski Filip', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Koptas Wiktor', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Kornobis Igor', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Kosidis Michalis', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Kosior Mikolaj', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Kostorz Kacper', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Koútris Leonárdo', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kowalczyk Mateusz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kowalski Jakub', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Kozik Miłosz', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Kozlovský Samuel', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kozłowski Eryk', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Kozubal Antoni', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Krajewski Marcel', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Krasniqi Ermal', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Krawczyk Piotr', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Król Michał', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Krzepisz Kacper', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Krzywański Jan', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.80, 'Pewny'),
('Kubica Krzysztof', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kubicki Jarosław', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Kucharczyk Kacper', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Kudła Dawid', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kukulski Patryk', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Kun Dominik', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kun Patryk', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Kurminowski Dawid', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Kurzawa Rafał', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Kusztal Patryk', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Kuusk Märten', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Lachowicz Oskar', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 0.80, 'Pewny'),
('Leândro Rossi Pereira', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Lecoeuche Quentin', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Lejman Jakub', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Leszczyński Rafał', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Leśniak Oskar', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Lewandowski Franciszek', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Lewicki Jakub', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Lis Jakub', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.30, 'Pewny'),
('Liseth Sondre', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Lisman Kornel', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Lisowski Wojciech', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Listkowski Marcin', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Liszewski Piotr', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Lokilo Jason', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Lončar Danijel', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Lopes Vasco', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Loska Tomasz', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Lozano Sergio', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('López Iván', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.80, 'Pewny'),
('Luberecki Filip', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Lubowiecki Kamil', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Lučić Luka', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Lukoszek Kamil', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Łabojko Jakub', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Łaski Wojciech', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Ława Natan', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Ławniczak Aleks', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Łodziński Filip', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.00, 'Pewny'),
('Łubik Marcel', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Łukasiak Kacper', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Łukowski Jakub', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Madej Leon', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Madejski Sebastian', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Maigaard Mikkel', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Majchrowicz Filip', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Majchrzak Jordan', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Makowski Tomasz', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Makuch Patryk', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Mamla Rafał', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Marcinkowski Jakub', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.30, 'Pewny'),
('Marcjanik Michał', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Maria Aurélio Laurindo', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Markovic Eman', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Marsenić Matija', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Marzec Mateusz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Masoero Lucas', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Massimo Roberto', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Matthys Hervé', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Matuszewski Konrad', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Matysek Adam', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Maurides Roque Júnior', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Mazurek Bartosz', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Mądrzyk Jakub', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Mena Camilo', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Mendes-Dudziński Marcel', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.30, 'Pewny'),
('Mendy Benjamin', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Meyer Paskal', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Michalski Damian', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Mijuśković Nemanja', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Mikielewicz Michał', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Milewski Sebastian', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Milić Antonio', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Minczew Martin', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Minuczyc Kacper', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Mirčetić Bogdan', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Mleczko Miłosz', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Mokwa Tomasz', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Molendowski Mikołaj', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Molnár Rajmund', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Mońka Wojciech', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Morag Arkadiusz', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Mosór Ariel', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Moutinho João', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Mozie Pascal', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Mrosek Noah', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Mrozek Bartosz', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Mróz Marek', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Mucha Szczepan', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.00, 'Pewny'),
('Mukairu Paul', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Murawski Radosław', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('N''Diaye Mbaye', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('N''Diaye Mor', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Najemski Arkadiusz', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Nalepa Michał', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Nastić Bojan', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Navarro Marc', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Nawrocki Kuba', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Neugebauer Tomasz', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Nguiamba Aurélien', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Niárchos Giánnis', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Niedbała Michał', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Nikołow Władimir', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Niski Nikodem', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Niziołek Alex', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Nowak Bartosz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Nowak Wiktor', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.80, 'Pewny'),
('Nowogoński Kamil', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Nsame Jean-Pierre', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Oliveira João', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Olkowski Paweł', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Olsson Elias', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Orlikowski Igor', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Otieno Erick', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Ouattara Zié', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Ouma Timothy', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Ólafsson Davíð', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Pacheco Dani', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Palacz Krystian', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Palma Luis', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Paluszek Aleksander', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Pankiewicz Szymon', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Pankov Radovan', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Paryzek Patryk', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Paszko Kyryło', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Paulsen Alex', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Pawlak Aleksander', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Pawłowski Bartłomiej', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Pedro Joao', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Pelmard Andy', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Percan Diego', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Perea Luis', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Pereira Joel', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Perković Mauro', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Peškovič Alex', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Petrović Zvonimir', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Piątkowski Kamil', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Piekutowski Miłosz', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Pieńko Tomasz', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Pietryga Piotr', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Pietrzyk Kacper', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Pietuszewski Oskar', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Pięczek Marcel', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Piła Dominik', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Pingot Maksymilian', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Pitan Levis', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Plach František', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Planeta Tomasz', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Plichta Kacper', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Pllana Bujar', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Podolski Lukas', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Polak Cezary', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Polak Dawid', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Pomietło Mateusz', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Pomorski Krystian', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Popielec Cyprian', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Popow Wiktor', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Pozo Alejandro', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Pozo José', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Praszelik Mateusz', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Predenkiewicz Marcel', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Prip Louka', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Pruchniewski Mateusz', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Pruszkowski Stanisław', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Przyborek Adrian', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Przybułek Filip', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Pululu Afimico', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 2.70, 'Pewny'),
('Putiwcew Artem', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Racovițan Bogdan', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Radwański Adam', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Rajović Mileta', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Rakoczy Michał', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Rállis Dimítris', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Ratajczyk Adam', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Ravas Henrich', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Reca Arkadiusz', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Reguła Marcel', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.30, 'Pewny'),
('Rejczyk Filip', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.00, 'Pewny'),
('Remacle Martin', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Renyer', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Repka Oskar', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Resta Pau', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Rivas Juande', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Rocha Leonardo', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Rodin Matej', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Rodrigues Ivo', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Rodríguez Pablo', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Rogala Grzegorz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Rogelj Žan', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Romanczuk Taras', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Ronaldo Fábio', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Rondić Imad', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Rosołek Maciej', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Rubežić Slobodan', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Rusyn Nazarij', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Rychta Dawid', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Rzuchowski Michał', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Sáček Michal', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Šahinović Muhamed', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Salamon Bartosz', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Salvador Iban', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Samper Sergi', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Sanca Leandro', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Sarnawśkyj Bohdan', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Sawicki Wiktor', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Scalet Mathieu', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Seck Ibrahima', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Sekulski Łukasz', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Selahi Lindon', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Seweryś Radosław', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Sezonienko Kacper', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Shehu Juljan', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Sidibe Alassane', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Silva Jean Carlos', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Sinkiewicz Dorian', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Skoczylas Mateusz', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Skrzypczak Mateusz', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Smolarczyk Bartłomiej', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Smoliński Kacper', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Sobczak Szymon', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Sochań Kamil', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.10, 'Pewny'),
('Sotiríou Konstantínos', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Sow Ousmane', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Stachowicz Nikodem', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Stanowski Kacper', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Stojanović Petar', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Stojilković Filip', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 2.30, 'Pewny'),
('Stojinović Dušan', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Stolarski Paweł', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Stolc Przemysław', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Strączek Rafał', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Struski Karol', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Strzałek Igor', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Strzeboński Miłosz', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Šutalo Boško', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Svarnas Stratos', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Svetlin Tamar', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Swatowski Miłosz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Sylla Youssuf', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Sypek Jakub', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Szafranek Wojciech', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Szafrański Radosław', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Szala Dominik', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Szczepaniak Mateusz', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Szczepankiewicz Bartosz', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Szcześniak Kryspin', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Szczuka Patryk', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Szkurin Ilja', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Szmyt Kajetan', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Szymanek Kacper', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Szymański Damian', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Szymański Karol', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.50, 'Pewny'),
('Szymański Marcel', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Szysz Patryk', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Tapsoba Abdoul', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Tavares Tomás', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Teklić Tonio', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Therkildsen Peter', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Thordarson Gisli', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Tobiasz Kacper', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Tobolik Aleksander', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Tomasiewicz Grzegorz', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Tomaszewski Bartosz', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Tomczyk Oskar', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Topór Eric', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Traoré Brahim', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Tratnik Gašper', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Trelowski Kacper', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Trepka Łukasz', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Trubeha Andrzej', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Tudor Fran', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Turek Radosław', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Twumasi Emmanuel', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Ulvestad Fredrik', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 2.30, 'Pewny'),
('Urban Damian', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Urbański Kacper', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.30, 'Pewny'),
('Urbański Wojciech', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Vallejo Hugo', (SELECT id FROM teams WHERE name LIKE '%Piast Gliwice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('van Hoeven Bradly', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Vereshchak Volodymyr', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Vinagre Rúben', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Visus Ricardo', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Vital Bernardo', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Vitalucci Hide', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Vojtko Matus', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Volanákis Polydéfkis', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Waclawek Bruno', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Wahlqvist Linus', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Walczak Tomasz', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.10, 'Pewny'),
('Wålemark Patrik', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 2.30, 'Pewny'),
('Wasielewski Marcin', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Wdowiak Mateusz', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Wdowik Bartłomiej', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Weirauch Szymon', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Weißhaupt Noah', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Wendt Karl', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Wędrychowski Marcel', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Węglarz Damian', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Wichtowski Maciej', (SELECT id FROM teams WHERE name LIKE '%Lech Poznań%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Więckowski Marcin', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Wilson-Esbrand Joshua', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Wjunnyk Bohdan', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Wojciechowski Maciej', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Wojtuszek Norbert', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Wolski Bartosz', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Wolski Maciej', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.60, 'Pewny'),
('Wolski Rafał', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Woźniak Arkadiusz', (SELECT id FROM teams WHERE name LIKE '%Zagłębie Lubin%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Wójcik Filip', (SELECT id FROM teams WHERE name LIKE '%Motor Lublin%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Wójcik Oskar', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 1.20, 'Pewny'),
('Wójtowicz Tomasz', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Wszołek Paweł', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 2.10, 'Pewny'),
('Wyganowski Aleksander', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Zahiroleslam Kahveh', (SELECT id FROM teams WHERE name LIKE '%Cracovia%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Zahovič Luka', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 2.00, 'Pewny'),
('Zając Filip', (SELECT id FROM teams WHERE name LIKE '%Wisła Płock%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Zapolnik Kamil', (SELECT id FROM teams WHERE name LIKE '%Termalica B-B%' LIMIT 1), 'MID', 1.90, 'Pewny'),
('Zator Dominick', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Zawadzki Jakub', (SELECT id FROM teams WHERE name LIKE '%Pogoń Szczecin%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Zeqiri Andi', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 2.20, 'Pewny'),
('Zieliński Wojciech', (SELECT id FROM teams WHERE name LIKE '%Arka Gdynia%' LIMIT 1), 'MID', 0.90, 'Pewny'),
('Zielonka Nikodem', (SELECT id FROM teams WHERE name LIKE '%Górnik Zabrze%' LIMIT 1), 'MID', 1.00, 'Pewny'),
('Zimovski Guilherme', (SELECT id FROM teams WHERE name LIKE '%Radomiak Radom%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Zreľák Adam', (SELECT id FROM teams WHERE name LIKE '%GKS Katowice%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Zwoźny Hubert', (SELECT id FROM teams WHERE name LIKE '%Korona Kielce%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Zych Oliwier', (SELECT id FROM teams WHERE name LIKE '%Raków Częstochowa%' LIMIT 1), 'MID', 1.80, 'Pewny'),
('Żelizko Iwan', (SELECT id FROM teams WHERE name LIKE '%Lechia Gdańsk%' LIMIT 1), 'MID', 1.70, 'Pewny'),
('Żewłakow Jakub', (SELECT id FROM teams WHERE name LIKE '%Legia Warszawa%' LIMIT 1), 'MID', 0.70, 'Pewny'),
('Żynel Bartłomiej', (SELECT id FROM teams WHERE name LIKE '%Jagiellonia Białystok%' LIMIT 1), 'MID', 1.40, 'Pewny'),
('Żyro Mateusz', (SELECT id FROM teams WHERE name LIKE '%Widzew Łódź%' LIMIT 1), 'MID', 1.80, 'Pewny')
;

-- Statystyki:
-- Łącznie unikalnych zawodników: 639
-- Wstawiono do bazy: 582
-- Pominięto (brak ceny): 57
