INSERT INTO teams (name, short_code, is_active) VALUES 
('Górnik Zabrze', 'GZA', true),
('Jagiellonia Białystok', 'JAG', true),
('Cracovia', 'CRA', true),
('Korona Kielce', 'KOR', true),
('Wisła Płock', 'WPL', true),
('Lech Poznań', 'LPO', true),
('Legia Warszawa', 'LEG', true),
('Radomiak Radom', 'RAD', true),
('Raków Częstochowa', 'RAK', true),
('Zagłębie Lubin', 'ZLU', true),
('Widzew Łódź', 'WDZ', true),
('Pogoń Szczecin', 'POG', true),
('Arka Gdynia', 'ARG', true),
('Motor Lublin', 'MOT', true),
('Termalica B-B', 'TBB', true),
('GKS Katowice', 'GKS', true),
('Piast Gliwice', 'PIA', true),
('Lechia Gdańsk', 'LGD', true);
